import {workTerms} from './life.js?v=month08';
import {storyArt,storyArtKey} from './story-art.js?v=month08';
import {monthLength,isMonth,storyDays,phases,dateLabel} from './month.js?v=month08';
import {ensureEconomy,continueCareer,netWorth} from './economy.js?v=month08';
import {openFinance} from './finance-ui.js?v=month08';
import {guidance,relationshipNote} from './guidance.js?v=month08';
import {normaliseSave} from './storage.js?v=month08';
import {today} from './week.js?v=month08';
import {endingArt,endingKey} from './endings.js?v=month08';
import {openDevice} from './devices.js?v=month08';
import {places,createMoment} from './scenes.js?v=month08';
import {people,fresh,activities,act,choose,blocked,getScene} from './engine.js?v=month08';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const KEY='with-you-demo-v1';let state=null,focus='lin',toast='',page=0,reply=null,hideUI=false;try{const v=JSON.parse(localStorage.getItem(KEY));state=normaliseSave(v);}catch{}page=state?.storyPage||0;reply=state?.replyText||null;focus=state?.replyWho||'lin';const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast='浏览器存储不可用，本次进度仅保留在当前页面。';}};
let endingCollection=[];try{const saved=JSON.parse(localStorage.getItem('with-you-endings-v1'));if(Array.isArray(saved))endingCollection=saved.filter(k=>endingArt[k]);}catch{}
function modal(html){$('#modal').className='';$('#modal').innerHTML=html;$('#modal').showModal();}function close(){$('#modal').close();}
const home={name:'我的小小住处',place:'梧桐公寓 · 302',image:'assets/home-apartment.png',ambience:'回到家，慢慢安排自己的生活'};
function render(){const s=state,moment=s?.activityMoment;const ending=endingKey(s);const showEnding=ending&&!s?.pending&&!moment&&!reply;if(showEnding&&!endingCollection.includes(ending)){endingCollection.push(ending);try{localStorage.setItem('with-you-endings-v1',JSON.stringify(endingCollection));}catch{}}const sceneId=(s?.pending?storyArtKey(s):null)||(moment?moment.id:reply?(s?.replyArt||focus):showEnding?ending:'home');const p=storyArt[sceneId]||endingArt[sceneId]||(sceneId==='home'?home:people[sceneId]||places[sceneId]||home);const clock=moment||s;const isPlace=!!places[sceneId];$('#app').innerHTML=`<main class="game ${s?.pending||reply||moment?'in-story':''} ${sceneId==='home'?'at-home':''} ${showEnding?'ending-scene':''} ${hideUI?'hide-ui':''}" style="--scene:url('${p.image}')"><div class="backdrop"></div><div class="vignette"></div><header class="hud"><div class="clock"><span class="season">${s?.career?'经营季':'九月 · 初秋'}</span><strong>${s?.career?String(s.day-monthLength(s)):String(clock?.day||1).padStart(2,'0')}<small>${s?.career?' / 周':' / '+String(s?monthLength(s):30)}</small></strong><span class="time">${s?.career?'经营人生':s?.ended?(monthLength(s)===30?'第一个月结束':'第一周结束'):clock?.slot?'17:30 · 傍晚':'10:00 · 白天'}</span></div><div class="chapter"><span>With You</span><small>${s?.career?'第二章 &nbsp; 自己的事业':(s&&monthLength(s)===7?'第一章 &nbsp; 城市的第一周':'第一章 &nbsp; 城市的第一个月')}</small></div><nav><button data-nav="calendar">月历</button><button data-nav="journal">手记</button><button data-nav="gallery">回忆 <small>${(s?.gallery.length||0)+endingCollection.length}/${Object.keys({...people,...places,...storyArt,...endingArt}).length}</small></button><button data-nav="feedback">反馈</button><button id="restart" title="重新开始一段生活">↺ 重启</button></nav></header><div class="status-strip"><span>${s?esc(s.name):'旅人'}</span><span>余额 <b>¥ ${(s?.cash??1000).toLocaleString()}</b></span><span>精力 <b>${s?.energy??80}</b><i class="energy"><i style="width:${s?.energy??80}%"></i></i></span><span>能力 <b>Lv.${s?.skill??1}</b></span></div>${s?.pending?storyHTML():moment?momentHTML(moment):reply?`<div class="dialogue"><div class="dialogue-meta"><strong>${people[focus]?.name||p.name}</strong><span>这一刻，被记住了</span></div><p>${esc(reply)}</p><button class="next" id="continue">${s?.ended?'这一章的回忆':'告别她，回到家'} <span>▸</span></button></div>`:s?.ended?endingHTML():homeHTML()}${toast&&!s?.pending&&!reply&&!moment?`<div class="toast" role="status">${esc(toast)}</div>`:''}<footer><span>临川 · ${storyArt[sceneId]||endingArt[sceneId]||sceneId==='home'||isPlace?p.ambience:sceneId==='lin'?'窗外有雨，杯中有暖意':'画室里有淡淡的茶香'}</span><div><span>${s?.pending||reply||moment?'SPACE / 继续 &nbsp; · &nbsp; ':''}H / 隐藏界面</span><button id="hide-ui">${hideUI?'显示界面':'纯净画面'}</button></div></footer><button class="restore-ui" id="restore-ui">显示界面 · H</button></main>`;
$('#hide-ui').onclick=$('#restore-ui').onclick=()=>{hideUI=!hideUI;render();};$('#continue')?.addEventListener('click',()=>{reply=null;if(state){state.replyText=null;state.replyArt=null;save();}if(state?.activityMoment){state.activityMoment=null;save();}render();});document.querySelectorAll('[data-quick-action]').forEach(b=>b.onclick=()=>doAction(b.dataset.quickAction));document.querySelectorAll('[data-hub]').forEach(b=>b.onclick=()=>openHub(b.dataset.hub));$('#start')?.addEventListener('click',setup);$('#restart').onclick=()=>modal('<h2>重新开始？</h2><p>当前章节的进度会被覆盖。你可以先在「试玩反馈」导出记录。</p><div class="modal-actions"><button id="cancel">继续当前生活</button><button class="primary" id="confirm">开始新生活</button></div>'),$('#restart').addEventListener('click',()=>{$('#cancel').onclick=close;$('#confirm').onclick=()=>{close();setup();};});document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{if(state?.pending)return;focus=b.dataset.person;if(state){state.viewScene=focus;save();}render();});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>openPanel(b.dataset.nav));$('#art')?.addEventListener('click',()=>showArt(p.image,p.name));$('#next')?.addEventListener('click',()=>{page++;state.storyPage=page;save();render();});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const who=state.pending.who;const art=storyArtKey(state);const date=getScene(state).options[Number(b.dataset.choice)]?.date;const result=choose(state,Number(b.dataset.choice));state=result.state;state.storyPage=0;state.viewScene=who;focus=who;reply=result.response;state.replyArt=date?'ending-'+who:art;if(storyArt[art]&&!state.gallery.includes(art))state.gallery.push(art);state.replyText=reply;state.replyWho=who;toast='';save();render();});$('#career-continue')?.addEventListener('click',()=>{state=continueCareer(state);save();render();business();});$('#ending-gallery')?.addEventListener('click',()=>openPanel('gallery'));$('#ending-feedback')?.addEventListener('click',()=>openPanel('feedback'));}
function homeHTML(){const s=state;const total=s?Object.values(s.visits).reduce((a,b)=>a+b,0):0;const goal=guidance(s);return `<section class="home-heading"><div class="eyebrow">梧桐公寓 · 302 · ${s?.career?'自己的事业':today(s).title}</div><h1>${s?'欢迎回家，'+esc(s.name):'在这座城，有了自己的灯。'}</h1><p>${goal}</p></section>${s?`<button class="hotspot desk" data-hub="desk"><i>◇</i><span>书桌<small>工作 · 交易 · 公司</small></span></button><button class="hotspot phone" data-hub="phone"><i>◇</i><span>手机<small>联系人 · 近况</small></span></button><button class="hotspot door" data-hub="door"><i>◇</i><span>出门<small>看看今天想去哪里</small></span></button><div class="home-bottom"><div><span class="eyebrow">生活的痕迹</span><p>${s.logs.length>1?esc(s.logs.filter(x=>!x.startsWith('夜晚过去')).at(-1)):'纸箱还没有拆完，杯子已经有了自己的位置。'}</p></div>${quickPlanHTML(s)}</div>`:`<div class="home-start"><button class="primary" id="start">放下行李，开启新生活 →</button><p>三十天相识 · 从小生意到自己的事业</p></div>`}`;}
function quickPlanHTML(s){const terms=workTerms(s);return `<div class="quick-plan"><span>常用安排 · 每次${s.career?'推进一周':'半天'}</span><div>${[['work',terms.polished?'精修工作':'常规工作',`+¥${terms.pay} · 精力−${terms.energy}`],['study','学习','−¥80 · 精力−12'],['rest','河边休息',`免费 · 精力+${Math.min(30,100-s.energy)}`]].map(([id,label,detail])=>{const reason=blocked(s,id);return `<button data-quick-action="${id}" ${reason?'disabled':''} title="${esc(reason||detail)}"><b>${label}</b><small>${esc(reason||detail)}</small></button>`;}).join('')}</div></div>`;}
function doAction(id){try{const before=state;state=act(state,id);state.viewScene=id;if(people[id])focus=id;else{state.activityMoment=createMoment(before,state,id);state.sceneVisits={...before.sceneVisits,[id]:(before.sceneVisits?.[id]||0)+1};if(!state.gallery.includes(id))state.gallery.push(id);}page=0;state.storyPage=0;toast='';close();save();render();}catch(e){const el=$('#hub-error');if(el)el.textContent=e.message;}}
function actionCard(id,label){const a=activities.find(a=>a.id===id),reason=blocked(state,id);return `<button class="hub-action" data-launch="${id}" ${reason?'disabled':''}><span>${label||a.title}</span><small>${reason||a.hint}</small><b>→</b></button>`;}
function business(){openFinance({state,modal,commit:s=>{state=s;save();render();},advance:doAction});}
function openHub(kind){openDevice(kind,{state,modal,close,launch:doAction,save,business});}
function momentHTML(moment){const p=places[moment.id];return `<div class="moment-location"><span>${state.career?'WEEK '+(moment.day-monthLength(state)):'DAY '+String(moment.day).padStart(2,'0')} / ${moment.slot?'傍晚':'白天'}</span><h2>${p.place}</h2></div><div class="dialogue activity-dialogue"><div class="dialogue-meta"><strong>${esc(state.name)} · 心声</strong><span>${p.name}</span></div><p>${esc(moment.text)}</p><div class="moment-results">${moment.changes.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${moment.economyReport?`<p class="settlement-note">经营结算：${esc(moment.economyReport)}</p>`:''}<button class="next" id="continue">${state.ended?'看看这一章的回忆':'收好这一刻，回家'} <span>▸</span></button></div>`;}
function storyHTML(){const scene=getScene(state);page=Math.min(page,scene.lines.length-1);const last=page===scene.lines.length-1;return `<div class="dialogue"><div class="dialogue-meta"><strong>${scene.name}</strong><span>${scene.title} · ${page+1}/${scene.lines.length}</span></div><p>${esc(scene.lines[page])}</p>${last?`${state.pending.weekend?'<p class="choice-context">答应邀约，就在这一章认真了解她；和其他人的相处会保持朋友关系。</p>':''}<div class="choices">${scene.options.map((o,i)=>{const lock=o.requires&&!o.requires(state);return `<button data-choice="${i}" ${lock?'disabled':''}>${esc(o.label)} ${lock?`<small>🔒 ${o.lock}</small>`:'<span>↗</span>'}</button>`;}).join('')}</div>`:'<button class="next" id="next">继续阅读 →</button>'}</div>`;}
function endingHTML(){return `<div class="ending"><div class="eyebrow">CHAPTER COMPLETE · ${monthLength(state)===30?'第一个月完成':'第一章完'}</div><h2>${state.ending.title}</h2><p>${state.ending.text}</p><div class="ending-actions"><button class="primary" id="career-continue">继续人生 · 开始经营 →</button><button class="ending-secondary" id="ending-gallery">回看结局 CG</button><button class="ending-secondary" id="ending-feedback">留下试玩感受 ↗</button></div><span>故事会在你的反馈里，继续生长。</span></div>`;}
function setup(){modal(`<div class="eyebrow">WELCOME TO LINCHUAN</div><h2>这次，做你自己。</h2><p>24 岁的初秋，你决定换一座城市生活。<br>第一章三十天，每天两个时段；完成后可继续按周经营。<br>书桌里的经营台可交易、开公司、拍电影。</p><form id="setup"><label>希望她们怎么称呼你？<input name="name" maxlength="16" placeholder="输入你的名字" value="旅人" required></label><label>带着什么出发？<select name="background"><option value="new">普通的开始 · ¥1,000 / 能力 1</option><option value="work">一点工作积蓄 · ¥1,600 / 能力 1</option><option value="study">刚完成进修 · ¥1,000 / 能力 3</option></select></label><p class="muted">你可以自由选择亲近谁，也可以专注自己的生活。<br>所有角色均为成年人。</p><button class="primary">开启我的第一个月 →</button><button type="button" id="cancel">暂时返回</button></form>`);$('#cancel').onclick=close;$('#setup').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state=fresh(d.get('name'),d.get('background'));ensureEconomy(state);focus='lin';page=0;reply=null;toast='行李已经放好。先工作、探索城市，或者与新邻居打个招呼。';save();close();render();};}
function showArt(src,name){modal(`<button class="modal-close" aria-label="关闭">×</button><img class="full-art" src="${src}" alt="${name} 剧情画面"><p>${name} · 初秋的记忆</p>`);$('.modal-close').onclick=close;}
function openPanel(type){if(type==='calendar'){modal(calendarHTML());}if(type==='journal'){modal(`<button class="modal-close" aria-label="关闭">×</button><div class="eyebrow">LIFE JOURNAL</div><h2>生活手记</h2>${state?`<div class="relationship-notes">${Object.entries(people).map(([id,p])=>`<span><strong>${p.name}</strong><small>${relationshipNote(state,id)}</small><small>相处 ${state.visits[id]} 次 · 亲近 ${state.rel[id]}</small></span>`).join('')}</div>`:''}<div class="journal">${state?state.logs.map(x=>`<p>${esc(x)}</p>`).join(''):'你的故事还没有开始。'}</div>`);}if(type==='gallery'){modal(`<button class="modal-close" aria-label="关闭">×</button><div class="eyebrow">MEMORIES</div><h2>那些想留住的瞬间</h2><p>完成一次行动或一段相处，收藏属于你的城市记忆。结局画面在重新开始后仍会保留。</p><div class="gallery">${Object.entries({...people,...places,...storyArt,...endingArt}).map(([id,p])=>(state?.gallery.includes(id)||endingCollection.includes(id))?`<button data-gallery="${id}"><img src="${p.image}" alt="${p.name}"><span>${p.name} · ${endingArt[id]?'结局回忆':storyArt[id]?'相处记忆':places[id]?'城市日常':id==='lin'?'雨声里的温度':'落日里的画室'}</span></button>`:`<div class="locked">◇<p>尚未解锁 · ${p.name}</p></div>`).join('')}</div>`);document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>{const p=storyArt[b.dataset.gallery]||people[b.dataset.gallery]||places[b.dataset.gallery]||endingArt[b.dataset.gallery];close();showArt(p.image,p.name);});}if(type==='feedback'){modal(`<button class="modal-close" aria-label="关闭">×</button><div class="eyebrow">LET'S SHAPE THIS STORY</div><h2>你想让故事怎样生长？</h2><p>不用懂游戏设计，告诉我你的直觉就好。</p><form id="feedback"><label>这版最想调整什么？<select name="dimension"><option>人物与 CG 画风</option><option>剧情、对白与心动感</option><option>生活养成与自由度</option><option>选择的影响与游戏难度</option><option>界面、操作与节奏</option></select></label><label>哪个瞬间喜欢，哪里无聊？<textarea name="notes" rows="4" placeholder="例如：人物再偏插画一点；想有手机聊天；工作太像点按钮……"></textarea></label><button class="primary">下载反馈与本局记录 ↓</button><p class="muted">文件保存在你的设备上。把文件或感受发给我，作为下一轮迭代依据。</p><p id="export-status" role="status"></p></form>`);$('#feedback').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const blob=new Blob([JSON.stringify({demo:'With You · 经营原型',feedback:d,playthrough:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='with-you-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#export-status').textContent='反馈文件已生成，可以在浏览器下载中查看。';};}$('.modal-close')?.addEventListener('click',close);}
document.addEventListener('keydown',e=>{if($('#modal').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==='h'){hideUI=!hideUI;render();}if(e.code==='Space'&&!hideUI){const next=$('#next')||$('#continue');if(next){e.preventDefault();next.click();}}});
// Device settings can change the home action preview; refresh on every dismissal path.
$('#modal').addEventListener('close',render);
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});render();

function calendarHTML(){if(!state)return '<button class="modal-close" aria-label="关闭">×</button><h2>城市月历</h2><p>开始新生活后，月历会记下你的安排。</p>';const s=state,length=monthLength(s),monthly=length===30;
return `<button class="modal-close" aria-label="关闭">×</button><h2>城市${monthly?'月':'周'}历 · ${s.career||s.ended?'章节已完成':dateLabel(s)}</h2><p>${monthly?'每天两个行动时段。故事按日期开放，错过当天仍可稍后见面；月底会为这一章收束。':'这是原七天存档。每天两个行动时段，周日为这一章收束；重启后可体验新的30天故事。'}</p>${monthly?`<div class="month-phases">${phases.map(p=>`<p><strong>${p.title}</strong><br>${p.goal}</p>`).join('')}</div>`:''}<div class="month-grid">${Array.from({length},(_,i)=>{const day=i+1;const event=day===length?(monthly?'月底相约':'周日相约'):monthly?(storyDays.includes(day)?'新的相处':'生活与经营'):'生活与相处';return `<div class="${day===s.day?'current':''} ${day<s.day?'past':''}"><b>${day}</b><small>${event}</small></div>`;}).join('')}</div><div class="relationship-notes">${Object.entries(people).map(([id,p])=>`<span><strong>${p.name}</strong><small>${relationshipNote(s,id)}</small><small>相处 ${s.visits[id]} 次 · 亲近 ${s.rel[id]}</small><small>${s.ended?'本章已结束 · 留在回忆中':s.career?'按自己的节奏继续相处':esc(blocked(s,id)||(s.visits[id]===0?'今天可以初次见面':s.day===length?'今天可以相约':'今天可以继续相处'))}</small></span>`).join('')}</div>`;}
