import {monthLength} from './month.js?v=month08';
export const goods=[{id:'coffee',name:'咖啡豆',base:40,kind:'商品'},{id:'chips',name:'电子元件',base:120,kind:'商品'},{id:'outdoor',name:'户外装备',base:80,kind:'商品'},{id:'cloud',name:'云帆科技',base:60,kind:'股票'},{id:'food',name:'四季消费',base:35,kind:'股票'}];
export const sectors={studio:{name:'创意工作室',cost:3000,revenue:1100,expense:450},shop:{name:'城市零售',cost:6000,revenue:2100,expense:1000},tech:{name:'软件公司',cost:12000,revenue:3800,expense:1500}};
export function ensureEconomy(s){if(s.economy)return s.economy;return s.economy={seed:Math.floor(Math.random()*4294967295)>>>0,period:0,prices:Object.fromEntries(goods.map(g=>[g.id,g.base])),history:Object.fromEntries(goods.map(g=>[g.id,[g.base]])),holdings:{},news:'新一轮城市交易开市。报价随时间变化，买卖各收取2%费用。',trend:0,company:null,films:[],tickets:0,lastReport:[],ledger:[],peak:s.cash};}
function random(e){e.seed=(Math.imul(e.seed,1664525)+1013904223)>>>0;return e.seed/4294967296;}
export function netWorth(s){const e=ensureEconomy(s);return Math.round(s.cash+Object.entries(e.holdings).reduce((v,[id,h])=>v+h.qty*e.prices[id]*.98,0)+(e.company?.capital||0)*.7+e.films.filter(f=>f.left>0).reduce((v,f)=>v+f.budget,0));}
export const upgradeCost=e=>e.company?Math.round(sectors[e.company.sector].cost*3**e.company.level):0;
export function transact(state,action,id,amount=1){const s=JSON.parse(JSON.stringify(state)),e=ensureEconomy(s);if(s.pending||s.activityMoment||s.replyText||s.ended)throw Error('先完成当前剧情或回顾，再安排经营');const spend=n=>{if(s.cash<n)throw Error('可用现金不足，可以卖出持仓或继续工作');s.cash-=n;};let message='';
if(action==='buy'||action==='sell'){if(!goods.some(g=>g.id===id)||!Number.isSafeInteger(amount)||amount<1||amount>100000000)throw Error('请输入有效的交易数量');const price=e.prices[id];const h=e.holdings[id]||{qty:0,cost:0};if(action==='buy'){const cost=Math.ceil(price*amount*1.02);spend(cost);h.cost+=cost;h.qty+=amount;message=`买入${goods.find(g=>g.id===id).name} ×${amount}，含费 ¥${cost}`;}else{if(h.qty<amount)throw Error('持仓数量不足');const income=Math.floor(price*amount*.98);h.cost*=1-amount/h.qty;h.qty-=amount;s.cash+=income;message=`卖出${goods.find(g=>g.id===id).name} ×${amount}，到账 ¥${income}`;}e.holdings[id]=h;}
else if(action==='found'){if(e.company||!sectors[id])throw Error('当前只能经营一家公司');spend(sectors[id].cost);e.company={sector:id,level:1,capital:sectors[id].cost,strategy:'steady',paused:false,last:0};message=`创办${sectors[id].name}，首期投入 ¥${sectors[id].cost}`;}
else if(action==='strategy'){if(!e.company||!['steady','growth','pause'].includes(id))throw Error('无效经营策略');e.company.strategy=id;message=`调整公司策略：${{steady:'稳健经营',growth:'积极拓客',pause:'暂停营业'}[id]}`;}
else if(action==='upgrade'){if(!e.company||e.company.level>=12)throw Error('当前无法扩张');const cost=upgradeCost(e);spend(cost);e.company.capital+=cost;e.company.level++;message=`扩张至 ${e.company.level} 级，投入 ¥${cost}`;}
else if(action==='close'){if(!e.company)throw Error('尚无公司');const value=Math.floor(e.company.capital*.7);s.cash+=value;e.company=null;message=`清算公司，回收 ¥${value}`;}
else if(action==='lottery'){if(e.tickets>=5)throw Error('本期最多购买5张');spend(20);e.tickets++;message='购入一张城市彩券，下一期揭晓。';}
else if(action==='film'){if(e.films.some(f=>f.left>0))throw Error('先完成当前电影');if(!['warm','comedy','scifi'].includes(id))throw Error('请选择电影题材');const budget=amount===10000000?10000000:5000;if(budget===10000000&&netWorth(s)<100000000)throw Error('长片产业需净资产达到1亿');if(!e.company)throw Error('先成立公司，组建制作班底');spend(budget);e.films.push({genre:id,budget,left:2,started:e.period,return:0});message=`启动${budget===5000?'独立短片':'院线长片'}，预算 ¥${budget}，两期后结算`;}
else throw Error('未知经营指令');e.ledger.push(`第${e.period}期：${message}`);e.ledger=e.ledger.slice(-80);s.logs.push(message);return {state:s,message};}
export function tickEconomy(s){const e=ensureEconomy(s);e.period++;const report=[];const event=Math.floor(random(e)*5);e.trend=event;const news=['消费节开幕，咖啡豆与消费股需求走强','科技订单增长，元件和科技股受到关注','户外季到来，装备需求回暖','市场观望，需求整体偏弱','城市影展开启，温情题材受到关注'];e.news=news[event];for(const g of goods){const favored=(event===0&&['coffee','food'].includes(g.id))||(event===1&&['chips','cloud'].includes(g.id))||(event===2&&g.id==='outdoor');const change=(random(e)-.5)*.36+(favored?.16:event===3?-.12:0);e.prices[g.id]=Math.max(3,Math.round(e.prices[g.id]*(1+change)));e.history[g.id].push(e.prices[g.id]);e.history[g.id]=e.history[g.id].slice(-12);}
if(e.company){const c=e.company,b=sectors[c.sector],scale=3**(c.level-1);if(c.strategy==='pause'){c.last=0;c.paused=true;report.push('公司暂停营业，无收入或运营支出');}else{const growth=c.strategy==='growth',expense=Math.round(b.expense*scale*(growth?1.7:1));if(s.cash<expense){c.paused=true;c.last=0;report.push(`公司本期需要 ¥${expense} 周转现金，结算时有 ¥${s.cash}，尚缺 ¥${expense-s.cash}；本期暂停接单，持仓不会自动卖出`);}else{c.paused=false;const revenue=Math.round(b.revenue*scale*(.55+random(e)*(growth?1.6:.8))*(event===3?.7:1));s.cash+=revenue-expense;c.last=revenue-expense;report.push(`公司收入 ¥${revenue}，支出 ¥${expense}，净现金流 ${c.last>=0?'+':''}${c.last}`);}}}
if(e.tickets){let prize=0;for(let i=0;i<e.tickets;i++){const r=random(e);prize+=r<.001?10000:r<.02?200:r<.15?20:0;}s.cash+=prize;report.push(`${e.tickets}张彩券开奖：奖金 ¥${prize}`);e.tickets=0;}
for(const f of e.films.filter(f=>f.left>0)){f.left--;if(!f.left){const favored=(f.genre==='warm'&&event===4)||(f.genre==='comedy'&&event===0)||(f.genre==='scifi'&&event===1);f.return=Math.round(f.budget*(.35+random(e)*1.9+(favored?.6:0)));s.cash+=f.return;report.push(`电影上映：分账收入 ¥${f.return}，${f.return>=f.budget?'盈利':'亏损'} ¥${Math.abs(f.return-f.budget)}`);}}
e.peak=Math.max(e.peak,netWorth(s));e.lastReport=report.length?report:['行情已更新。持仓盈亏尚未兑现，卖出后才计入现金。'];e.ledger.push(`第${e.period}期：${e.news}`, ...e.lastReport);e.ledger=e.ledger.slice(-80);s.logs.push(`经营第${e.period}期：${e.lastReport.join('；')}`);}
export function continueCareer(state){const s=JSON.parse(JSON.stringify(state));if(!s.ended)throw Error('先完成当前章节');s.chapterEnding=s.ending;s.partner=s.ending?.who||null;s.ended=false;s.ending=s.partner;s.career=true;s.day=monthLength(s)+1;s.slot=0;s.replyText=null;s.replyArt=null;s.activityMoment=null;ensureEconomy(s);s.logs.push('这一章结束。接下来，每次生活行动推进一周，继续经营自己的人生。');return s;}
