import {monthFinale} from './month-finale.js?v=month08';
import {storyArt,storyArtKey} from './story-art.js?v=month08';
import {monthLength,isMonth,storyDays} from './month.js?v=month08';
import {monthStory} from './month-stories.js?v=month08';
import {tickEconomy} from './economy.js?v=month08';
import {workTerms} from './life.js?v=month08';
import {conclusion} from './conclusion.js?v=month08';
import {extraStory} from './extra-stories.js?v=month08';
export const people={lin:{name:'林知夏',job:'25 岁 · 品牌策划',image:'assets/lin-cafe.png',place:'街角 · 雨声咖啡',intro:'习惯把一切安排妥当，也在学习坦白自己的不安。'},shen:{name:'沈以宁',job:'26 岁 · 自由插画师',image:'assets/shen-studio.png',place:'楼顶 · 拾光工作室',intro:'把城市画得很温柔，却总把自己的作品藏到最后。'}};
export const fresh=(name='旅人',background='new',campaignDays=30)=>({version:1,campaignDays:campaignDays===7?7:30,name:name.trim().slice(0,16)||'旅人',background,day:1,slot:0,cash:background==='work'?1600:1000,energy:80,skill:background==='study'?3:1,rel:{lin:0,shen:0},visits:{lin:0,shen:0},flags:{},gallery:[],logs:['你带着一只行李箱，搬进了临川。'],pending:null,ended:false,ending:null});
export const activities=[{id:'work',title:'认真工作',icon:'↗',desc:'把手上的小项目做好',hint:'收入 +260 起 · 精力 −18'},{id:'study',title:'给自己充电',icon:'▤',desc:'上一节课，拓宽一点可能',hint:'能力 +1 · ¥80 · 精力 −12'},{id:'rest',title:'留一点空白',icon:'☁',desc:'散步、吃饭，好好休息',hint:'精力 +30 · 免费'},{id:'lin',title:'去雨声咖啡',icon:'☕',desc:'知夏常在这里整理提案',hint:'一段相处 · ¥45 · 精力 −10'},{id:'shen',title:'敲敲工作室的门',icon:'✧',desc:'以宁说，那里总有热茶',hint:'一段相处 · ¥35 · 精力 −10'}];
export function blocked(s,id){if(s.ended||s.pending)return '请先完成当前剧情';const cost={work:[0,workTerms(s).energy],study:[80,12],rest:[0,0],lin:[45,10],shen:[35,10]}[id];if(!cost)return '未知活动';if(people[id]&&s.flags['metDay'+id]===s.day)return '今天已经见过面了，明天再聊新的故事';if(people[id]&&isMonth(s)&&s.day<monthLength(s)){const next=storyDays[s.visits[id]];if(next===undefined)return '这个月的故事已走到约定前，30日再相见';if(s.day<next)return `她约你第 ${next} 天再见；今天先安排自己的生活`;}if(people[id]&&!isMonth(s)&&s.visits[id]>=5&&s.day<7)return '周末的邀约已留下，周日再相见';if(people[id]&&!s.career&&s.flags['sunday'+id])return '今天已经相聚过，留一点时间给自己';if(s.cash<cost[0])return '余额不足，先工作或休息';if(s.energy<cost[1])return '有些累了，先休息一下';return '';}
function advance(s){if(s.career){s.day++;s.slot=0;s.energy=Math.min(100,s.energy+12);tickEconomy(s);return;}s.slot++;if(s.slot===2){s.slot=0;s.day++;if(s.economy)tickEconomy(s);const recovery=Math.min(12,100-s.energy);s.energy+=recovery;s.logs.push(`夜晚过去，好好睡了一觉。精力 +${recovery}。`);}if(s.day>monthLength(s)){s.ended=true;s.day=monthLength(s);s.ending=conclusion(s);}}
export function act(state,id){const s=JSON.parse(JSON.stringify(state));const error=blocked(s,id);if(error)throw Error(error);const stamp=`第 ${s.day} 天 · ${s.slot?'傍晚':'白天'}`;if(people[id]){s.cash-=id==='lin'?45:35;s.energy-=10;s.pending={who:id,episode:Math.min(s.visits[id],isMonth(s)?11:4),weekend:s.day===monthLength(s)&&s.visits[id]>=2};s.logs.push(`${stamp}：去了${storyArt[storyArtKey(s)]?.place||people[id].place}。`);return s;}if(id==='work'){s.workCount=(s.workCount||0)+1;const terms=workTerms(s),pay=terms.pay;s.cash+=pay;s.energy-=terms.energy;if(terms.polished)s.flags.polishedWork=true;s.logs.push(`${stamp}：完成项目（${terms.polished?'精修':'常规'}），收入 ¥${pay}，精力 −${terms.energy}。`);}if(id==='study'){s.studyCount=(s.studyCount||0)+1;s.cash-=80;s.energy-=12;s.skill++;s.logs.push(`${stamp}：学会了一项新技能。能力 +1。`);}if(id==='rest'){s.restCount=(s.restCount||0)+1;s.energy=Math.min(100,s.energy+30);s.logs.push(`${stamp}：沿着河边慢慢走，终于放松下来。`);}advance(s);return s;}
export function choose(state,index){const s=JSON.parse(JSON.stringify(state));if(!s.pending)throw Error('没有待完成的剧情');const scene=getScene(s);const option=scene.options[index];if(!option||option.requires&&!option.requires(s))throw Error('尚未满足条件');const {who}=s.pending;s.flags['metDay'+who]=s.day;if(s.pending.weekend)s.flags['sunday'+who]=true;s.rel[who]+=option.points??1;s.visits[who]++;if(option.flag)s.flags[option.flag]=true;if(!s.gallery.includes(who))s.gallery.push(who);if(option.date)s.ending=who;if(s.pending.weekend&&!option.date)s.flags['friends'+who]=true;s.logs.push(`${people[who].name}：你选择「${option.label}」。${option.response}`);s.pending=null;advance(s);return {state:s,response:option.response};}
export function getScene(s){const {who,episode,weekend}=s.pending;const p=people[who];if(isMonth(s)&&weekend)return monthFinale(s,who,p,people);if(isMonth(s)&&!weekend&&episode>=5)return {...p,...monthStory(s,who,episode)};if(s.career&&s.visits[who]>=5)return {...p,title:'各自忙碌，也一起生活',lines:[s.economy?.company?'你说起最近经营公司的起伏。她听完，先问你这周有没有好好休息。':'这次见面，你们聊起最近的小事，谁也没急着看手机。',who==='lin'?'“工作可以再安排，今天的咖啡先趁热喝。”她把杯子推到你面前。':'她翻开速写本，给你看这一周留在画里的街角。'],options:[{label:'放下行情，认真听她讲近况',points:1,response:'这半天没有新的交易，但你记住了她笑起来的样子。'},{label:'坦诚分享自己的压力',points:1,response:'她没有替你做决定。有人愿意听完，已经让你轻松了一些。'}]};if(!weekend&&episode>=3)return {...p,...extraStory(s,who,episode)};if(weekend)return {...p,title:isMonth(s)?'把下个月，也留一点给你':'把今天留给谁',lines:who==='lin'?['她今天没有带电脑。窗外的雨停了，咖啡还冒着热气。',s.flags.honestLin||s.flags.shareLin?'“听你说起自己的事，我很开心。”她看向你，“今天，继续慢慢聊，好吗？”':'“今天没有待办清单。”她看向你，“想听听你的事，也想说说工作以外的我。”']:['她把工作室的门敞开，窗边放着展览的导览册。','“今天河边有个小展览。要不要……和我一起去？”'],options:[{label:who==='lin'?'认真陪她，并约定下周再见':'一起去看展，并约定下次见面',points:2,date:true,requires:s=>s.rel[who]>=(isMonth(s)?12:4)&&s.visits[who]>=(isMonth(s)?6:2)&&(!s.ending||s.ending===who),lock:s.ending&&s.ending!==who?`你已与${people[s.ending].name}约定下周，本周保留这份约定`:isMonth(s)?'需要至少6次相处与亲近12；也可以作为朋友结束这个月':'需要至少两次真诚的相处（亲近 4）',response:who==='lin'?'你们在窗边坐到雨停，聊起小时候住过的街道和想吃的小店。杯里的咖啡凉了，这次谁也没有着急。“下次换一家。”她说，已经自然地把你放进下一周。':'她洗净画笔，和你走进河边的小展。入口右边，那张黄昏终于挂了起来。你们在画前站了很久。“以前我只敢想象有人停下来。”她轻声说，“现在你真的在这里。”'}, {label:s.ending&&s.ending!==who?'坦诚说明已有约定，以朋友身份相处':'坦诚说，想先从朋友慢慢了解',points:1,response:s.ending&&s.ending!==who?'她点了点头，感谢你把话说清楚。今天的相处留在朋友的位置，你们都不必猜测。':'她点了点头。你们都愿意给这段关系一点时间。'}]};
const stories={lin:[{title:'一杯刚好的温度',lines:['搬来临川的第一场雨，比天气预报早了半小时。你抱着湿掉的纸袋，在咖啡馆门口站了一会儿。','“这里没人。你的纸袋……好像快撑不住了。”她把椅子往外拉了拉，递来几张纸巾。','“我叫林知夏。刚搬来？我也是。只比你早三个月。”'],options:[{label:'接过纸巾：“那你算我的城市前辈了。”',points:2,response:'“前辈的第一条建议：这家的热拿铁，比天气预报可靠。”她笑了。'},{label:'道谢，问她附近有没有合适的工作机会',points:1,response:'她认真写下两个招聘平台。“先安顿下来，别太着急。”'}]}, {title:'完美提案的背面',lines:['知夏的咖啡已经凉了。屏幕上的提案，停在同一页很久。','“改了六遍。大家都说挺好的，可我总觉得……他们只是不好意思说。”','她揉了揉眉心。“抱歉，好像每次见你都在聊工作。”'],options:[{label:'“你可以先说说，最想留下的是哪一部分。”',points:2,flag:'listenLin',response:'她慢慢讲起最初的想法。说到一半，眼睛终于重新亮了起来。'},{label:'用学到的方法，陪她重新梳理提案',points:3,requires:s=>s.skill>=3,lock:'需要能力 3',response:'你们把六版方案铺在桌上，找到了她一直想表达的那一句话。'},{label:'“已经很好了，别给自己太大压力。”',points:1,response:'“嗯，我试试。”她笑了一下，又低头看向屏幕。'}]}, {title:'她记得的那句话',lines:[s.flags.listenLin?'“我把最想留下的那部分保住了。”她还记得你上次的问题。':'“提案过了。”这次，她终于在咖啡还热的时候喝了一口。','“以前我觉得，在新城市站稳脚跟，就得什么都自己扛。”','她停了停。“现在觉得，偶尔有人一起坐坐，也挺好。”'],options:[{label:'“下次难熬的时候，也可以找我。”',points:2,response:'“好。你也是。”她说得很轻，却没有移开目光。'},{label:'举起杯子：“为你庆祝一下。”',points:1,response:'瓷杯轻轻碰在一起。这个傍晚，多了一件值得记住的事。'}]}],shen:[{title:'楼上的陌生人',lines:['楼上有东西滚落的声音。你走出门，一支蓝色画笔停在脚边。','“抓到逃兵了吗？”短发女生从楼梯拐角探出头，袖口还沾着颜料。','“沈以宁。楼顶那间工作室是我的。要上来喝杯茶吗？”'],options:[{label:'“好啊。它是带我来参观的向导吗？”',points:2,response:'“那它今天算立功了。”她接过画笔，笑着替你推开门。'},{label:'问她接插画委托的工作是什么样的',points:1,response:'“一半画画，一半回消息。”她眨眨眼，“还有一点点熬夜。”'}]}, {title:'还没署名的画',lines:['以宁把一张画翻过去，又忍不住翻回来。那是河边很普通的黄昏。','“委托人喜欢热闹一点的。这张太安静了。”','“周末有个小展，我想投它。又怕……根本没人停下来看。”'],options:[{label:'说出画里吸引你的细节：“窗边那盏灯，让人想回家。”',points:2,flag:'seeShen',response:'她看着那一小块暖色。“你看到了啊。那是我最后加上去的。”'},{label:'“试一次吧，我想看你把它挂起来。”',points:2,response:'“那你得来。”她说完才意识到自己说得有多快。'},{label:'建议她先按市场喜欢的风格改改',points:0,response:'“嗯，工作稿会改的。”她轻轻把这张画收进自己的文件夹。'}]}, {title:'画面之外的人',lines:[s.flags.seeShen?'“那盏灯，我留下来了。”她把画靠在窗边，像在回答几天前的你。':'“我投了那张黄昏。”她故作随意，嘴角却藏不住笑。','她翻开另一本速写。你认出了自己经常坐的那把椅子。','“最近工作室好像没那么安静了。”'],options:[{label:'“以后我可以常来吗？”',points:2,response:'“茶杯都给你留好了。”她低头翻页，耳尖有一点红。'},{label:'认真夸她终于迈出了这一步',points:1,response:'“谢谢。那天如果没人听我说，我大概还在犹豫。”'}]}]};return {...p,...stories[who][episode]};}
