import {operatingCost,investmentPlan} from './finance-plan.js?v=month08';
import {goods,sectors,ensureEconomy,netWorth,transact,upgradeCost} from './economy.js?v=month08';
const money=n=>'¥'+Math.round(n).toLocaleString(),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openFinance({state,modal,commit,advance}){let s=state,tab='market',notice='';ensureEconomy(s);const root=document.querySelector('#modal');
function draw(){const e=s.economy,c=e.company,wealth=netWorth(s);modal(`<div class="finance"><header><div><small>LINCHUAN CAPITAL · 第 ${e.period} 期</small><h2>我的事业</h2></div><button id="finance-close" aria-label="关闭经营台">×</button></header><div class="finance-stats"><span>可用现金<b>${money(s.cash)}</b></span><span>净资产估值<b>${money(wealth)}</b></span><span>下一站<b>${wealth>=1e8?'亿元俱乐部':c?'扩张与电影':'第一家公司 · ¥3,000'}</b></span></div><p class="finance-news">${esc(e.news)}</p><nav>${[['market','市场与股票'],['company','公司经营'],['film','电影产业'],['lottery','城市彩券'],['ledger','现金流记录']].map(([id,t])=>`<button data-tab="${id}" aria-current="${tab===id}">${t}</button>`).join('')}</nav><section class="finance-content">${tab==='market'?market():tab==='company'?company():tab==='film'?film():tab==='lottery'?lottery():ledger()}</section><p class="finance-notice" role="status">${esc(notice)}</p><footer><div>交易与配置不耗时。${s.career?'每次生活行动推进一周。':'第一章每天结束更新一期。'}<br>下一期会更新行情、结算公司、开奖及推进拍摄。</div><button id="finance-next">${s.career?'休整并推进一周':'散步休息 · 推进半天'} →</button></footer></div>`);root.className='finance-shell';root.querySelector('#finance-close').onclick=()=>root.close();root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;notice='';draw();});root.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{try{const action=b.dataset.command,id=b.dataset.id;const input=root.querySelector(`[data-quantity="${id}"]`);const amount=input?Number(input.value):Number(b.dataset.amount||1);const result=transact(s,action,id,amount);s=result.state;notice=result.message;commit(s);draw();}catch(err){notice=err.message;root.querySelector('.finance-notice').textContent=notice;}});root.querySelector('#finance-next').onclick=()=>advance('rest');}
function plan(cost,nextCost){const p=investmentPlan(s,cost,nextCost);return `<p class="finance-plan">${p.affordable?`投入后可用现金 ${money(p.after)} · 下期运营成本 ${money(p.nextCost)}<br>${p.gap?`周转还差 ${money(p.gap)}，可先工作或变现再跨期。`:'已覆盖一期运营成本；后续收入未计入预览。'}`:`当前投入尚差 ${money(-p.after)}，下期运营成本 ${money(p.nextCost)}。`}</p>`;}
function market(){const e=s.economy;return `<p class="finance-help">报价为虚构市场。买卖各收2%费用；均价含买入费，浮盈亏按扣除卖出费估算。公司需留运营现金。</p><div class="market-grid">${goods.map(g=>{const h=e.holdings[g.id]||{qty:0,cost:0},hist=e.history[g.id],p=e.prices[g.id],prev=hist.at(-2)||p,pnl=h.qty*p*.98-h.cost;return `<article><small>${g.kind}</small><h3>${g.name}</h3><strong>${money(p)} <em class="${p>=prev?'up':'down'}">${((p/prev-1)*100).toFixed(1)}%</em></strong><div class="price-history">近${hist.length}期：${hist.join(' → ')}</div><p>持有 ${h.qty} · 均价 ${money(h.qty?h.cost/h.qty:0)}<br>浮动盈亏 <b>${money(pnl)}</b></p><label>数量 <input type="number" data-quantity="${g.id}" min="1" step="1" value="1" aria-label="${g.name}交易数量"></label><div><button data-command="buy" data-id="${g.id}">买入</button><button data-command="sell" data-id="${g.id}" ${h.qty?'':'disabled'}>卖出</button></div></article>`;}).join('')}</div>`;}
function company(){const e=s.economy,c=e.company;return c?`<h3>${sectors[c.sector].name} · Lv.${c.level}</h3><p>股权100% · 清算估值 ${money(c.capital*.7)} · 上期净现金流 ${money(c.last)}</p><p>基础每期运营成本 ${money(sectors[c.sector].expense*3**(c.level-1))}。积极拓客提高成本与收入波动；现金不足时自动停单，无借贷。</p><div class="finance-options">${[['steady','稳健经营'],['growth','积极拓客 · 成本×1.7'],['pause','暂停营业 · 收支归零']].map(([id,t])=>`<button data-command="strategy" data-id="${id}" aria-pressed="${c.strategy===id}">${t}</button>`).join('')}</div><p>扩张使基础营收与成本均×3。下期先支付成本再接单，持仓不自动变现。</p><button data-command="upgrade" ${c.level>=12?'disabled':''}>扩张一级 · ${money(upgradeCost(e))}</button>${c.level<12?plan(upgradeCost(e),operatingCost(e,c.level+1)):''}<details><summary>退出经营</summary><p>清算仅回收累计投入70%，该公司等级将清空。</p><button data-command="close">确认清算公司</button></details>`:`<p>选择第一家公司。成立后下期才开始经营，请在注册资金之外留够运营现金。</p><div class="market-grid">${Object.entries(sectors).map(([id,c])=>`<article><h3>${c.name}</h3><p>注册 ${money(c.cost)}<br>基础营收 ${money(c.revenue)}/期<br>运营成本 ${money(c.expense)}/期</p><button data-command="found" data-id="${id}">成立公司</button>${plan(c.cost,c.expense)}</article>`).join('')}</div><p class="finance-help">当前试玩支持一家公司与100%自持股权；上市融资留待后续扩展。</p>`;}
function film(){const e=s.economy,active=e.films.find(f=>f.left>0);return `<h3>从独立短片，到院线长片</h3><p>短片预算 ¥5,000，需拥有公司；长片预算 ¥10,000,000，净资产达到1亿后开放。占用资金两期，上映后一次分账，可能亏损。题材与上映时的市场热点匹配可提高收益。</p>${!active?'<h4>短片资金预览</h4>'+plan(5000)+(netWorth(s)>=1e8?'<h4>长片资金预览</h4>'+plan(10000000):''):''}${active?`<div class="finance-news">正在拍摄 · 剩余 ${active.left} 期 · 已投入 ${money(active.budget)}</div>`:`<div class="finance-options">${[['warm','温情'],['comedy','喜剧'],['scifi','科幻']].map(([id,name])=>`<article><h3>${name}</h3><button data-command="film" data-id="${id}" data-amount="5000">拍短片 · ¥5,000</button><button data-command="film" data-id="${id}" data-amount="10000000" ${netWorth(s)<1e8?'disabled':''}>院线长片 · 亿元俱乐部</button></article>`).join('')}</div>`}<p>已上映 ${e.films.filter(f=>!f.left).length} 部</p>${e.films.filter(f=>!f.left).map(f=>`<p>预算 ${money(f.budget)} → 分账 ${money(f.return)}</p>`).join('')}<p class="finance-help">本轮先实现电影产业；矿业与足球队尚未开放。</p>`;}
function lottery(){return `<h3>一张彩券，一点偶然</h3><p>每张 ¥20，每期最多5张，下期统一开奖。概率：0.1%得¥10,000；1.9%得¥200；13%得¥20；85%未中奖。每张期望返还¥16.40。</p><p>本期待开奖 ${s.economy.tickets}/5 张</p><button data-command="lottery" ${s.economy.tickets>=5?'disabled':''}>购买一张 · ¥20</button><p class="finance-help">仅使用游戏资金，无真实购买或兑奖。</p>`;}
function ledger(){return `<h3>最近一期结算</h3>${s.economy.lastReport.map(x=>`<p>${esc(x)}</p>`).join('')}<h3>交易与经营记录</h3>${s.economy.ledger.slice().reverse().map(x=>`<p>${esc(x)}</p>`).join('')||'<p>还没有交易。先留好周转资金，再选择第一笔投入。</p>'}`;}
draw();}
