// Preserve the original seven-day regression contract; monthly routes have separate tests.
const fresh=(name,background)=>baseFresh(name,background,7);
import test from 'node:test';import assert from 'node:assert/strict';import {fresh as baseFresh,act,choose,getScene,blocked}from'./engine.js';
test('14 actions reach a complete independent-life ending without negative resources',()=>{let s=fresh();for(let i=0;i<14;i++)s=act(s,i%2?'rest':'work');assert.equal(s.ended,true);assert.ok(s.ending.title);assert.ok(s.energy>=0);assert.equal(s.day,7);});
test('both relationship routes unlock and reach their ending',()=>{for(const who of ['lin','shen']){let s=fresh();for(let i=0;i<3;i++){s=act(s,who);s=choose(s,0).state;if(s.slot)s=act(s,'rest');}while(s.day<7)s=act(s,'rest');s=act(s,who);assert.ok(getScene(s).options[0].requires(s));s=choose(s,0).state;s=act(s,'rest');assert.equal(s.ending.who,who);assert.ok(s.gallery.includes(who));assert.ok(s.flags[who==='lin'?'listenLin':'seeShen']);}});
test('relationship and skill gates reject invalid choices',()=>{let s=fresh();s=choose(act(s,'lin'),0).state;s=act(s,'rest');s=act(s,'lin');assert.throws(()=>choose(s,1));s=choose(s,0).state;while(s.day<7)s=act(s,'rest');s=act(s,'shen');assert.equal(getScene(s).title,'楼上的陌生人');assert.ok(!getScene(s).options[0].date);});
test('pending scene survives serialization and blocks extra actions',()=>{const s=act(fresh(),'lin'),r=JSON.parse(JSON.stringify(s));assert.equal(getScene(r).title,'一杯刚好的温度');assert.throws(()=>act(r,'work'));assert.equal(choose(r,0).state.slot,1);});
test('low resources block paid activities, recovery remains possible',()=>{let s=fresh();s.cash=0;s.energy=0;assert.ok(blocked(s,'lin'));assert.ok(blocked(s,'work'));assert.equal(blocked(s,'rest'),'');s=act(s,'rest');assert.equal(s.energy,30);});

test("completed encounters cannot be farmed before Sunday",()=>{let s=fresh();for(let i=0;i<5;i++){s=choose(act(s,"lin"),0).state;if(i<4)s=act(s,"rest");}assert.ok(blocked(s,"lin"));assert.throws(()=>act(s,"lin"));});
import {endingKey,endingArt} from './endings.js';
test('all four completed routes resolve to distinct ending CGs',()=>{const results=[];for(const who of ['lin','shen',null]){let s=fresh();if(who){for(let i=0;i<2;i++){s=choose(act(s,who),0).state;s=act(s,'rest');}while(s.day<7)s=act(s,'rest');s=choose(act(s,who),0).state;s=act(s,'rest');}else for(let i=0;i<14;i++)s=act(s,'rest');results.push(endingKey(s));}let s=fresh('旅人','study');for(let i=0;i<3;i++)s=act(s,'study');while(!s.ended)s=act(s,'rest');results.push(endingKey(s));assert.equal(new Set(results).size,4);for(const id of results)assert.ok(endingArt[id].image);assert.equal(endingKey(fresh()),null);});
