// Preserve the original seven-day regression contract; monthly routes have separate tests.
const fresh=(name,background)=>baseFresh(name,background,7);
import test from 'node:test';import assert from 'node:assert/strict';
import {fresh as baseFresh,act} from '../engine.js';import {ensureEconomy,transact,tickEconomy,continueCareer,netWorth,upgradeCost} from '../economy.js';import {normaliseSave} from '../storage.js';
const setup=(cash=10000)=>{const s=fresh();s.cash=cash;ensureEconomy(s).seed=12345;return s;};
test('trade roundtrip pays both fees, cannot oversell or create cash using invalid quantities',()=>{let s=setup(1000);s=transact(s,'buy','coffee',10).state;assert.equal(s.cash,592);assert.equal(s.economy.holdings.coffee.qty,10);assert.throws(()=>transact(s,'sell','coffee',11));for(const n of [-1,0,1.5,NaN,Infinity])assert.throws(()=>transact(s,'buy','coffee',n));s=transact(s,'sell','coffee',10).state;assert.equal(s.cash,984);assert.equal(s.economy.holdings.coffee.cost,0);});
test('saved random stream produces identical market and lottery settlements',()=>{let s=transact(setup(),'lottery').state;const copy=JSON.parse(JSON.stringify(s));tickEconomy(s);tickEconomy(copy);assert.deepEqual(s,copy);assert.equal(s.economy.tickets,0);});
test('company requires liquidity and pauses safely rather than going negative',()=>{let s=transact(setup(3000),'found','studio').state;tickEconomy(s);assert.equal(s.cash,0);assert.equal(s.economy.company.paused,true);s.cash=1000;tickEconomy(s);assert.equal(s.economy.company.paused,false);assert.ok(s.cash>=0);s=transact(s,'strategy','pause').state;const cash=s.cash;tickEconomy(s);assert.equal(s.cash,cash);});
test('movie takes two periods, settles once, requires company and locks concurrent production',()=>{assert.throws(()=>transact(setup(),'film','warm',5000));let s=transact(setup(20000),'found','studio').state;s=transact(s,'strategy','pause').state;s=transact(s,'film','warm',5000).state;assert.throws(()=>transact(s,'film','scifi',5000));const cash=s.cash;tickEconomy(s);assert.equal(s.cash,cash);tickEconomy(s);const after=s.cash;assert.equal(after,cash+s.economy.films[0].return);tickEconomy(s);assert.equal(s.cash,after);assert.throws(()=>transact(s,'film','warm',10000000));});
test('lottery enforces limit and cannot buy on a pending scene',()=>{let s=setup();for(let i=0;i<5;i++)s=transact(s,'lottery').state;assert.throws(()=>transact(s,'lottery'));s.pending={};assert.throws(()=>transact(s,'buy','food',1));});
test('chapter converts to career without wiping relationships and advances exactly one period',()=>{let s=setup();for(let i=0;i<14;i++)s=act(s,'rest');assert.equal(s.economy.period,7);s=continueCareer(s);assert.equal(s.day,8);const r=act(s,'rest');assert.equal(r.day,9);assert.equal(r.economy.period,8);assert.equal(r.ended,false);assert.ok(normaliseSave(JSON.parse(JSON.stringify(r))));});
test('company growth makes billion-club film reachable without cheats or lottery',()=>{let s=setup(1000);for(let i=0;i<14;i++)s=act(s,i%2?'rest':'work');s=continueCareer(s);while(s.cash<3500)s=act(s,s.energy>=18?'work':'rest');s=transact(s,'found','studio').state;let weeks=0;while(netWorth(s)<110000000&&weeks<250){const c=s.economy.company,cost=upgradeCost(s.economy);if(c.level<12&&s.cash>=cost+450*3**c.level)s=transact(s,'upgrade').state;s=act(s,'rest');weeks++;assert.ok(s.cash>=0);}assert.ok(netWorth(s)>=110000000,`only ${netWorth(s)} after ${weeks} weeks`);s=transact(s,'film','warm',10000000).state;assert.equal(s.economy.films[0].budget,10000000);console.log(`经营路径：${weeks}周达到亿元俱乐部，净资产 ${netWorth(s)}`);});
